var dialogues = [
    {
        id:0,
        text: "正月初二，一个普普通通的一天，醒来已经将近中午。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/背景1.png",
        back: 0,
        next: 1,
    },
    {
        id:1,
        text: "今年我27岁了，我从小在养父母家长大，对亲生父母没有丝毫的印象。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/背景1.png",
        back: 0,
        next: 2,
    },
    {
        id:2,
        text: "昨天我已经去看过我的养父母了，他们也有自己亲生的孩子，也有自己的生活，所以今天我就回到了自己的公寓了，加之我还没有步入婚姻，所以这就是百无聊赖的一天。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/背景1.png",
        back: 1,
        next: 3,
    },
    {
        id:3,
        text: " ",
        name: "",
        saylihui: "",
        option: [{
            text: "不能再睡了，下床溜达溜达",
            next: 5,
        },],
        backlihui: "",
        background: "素材/背景/背景1.png",
        back: 2 ,
    },
    {
        id:4,
        text: "",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/背景1.png",
        back: 3,
        next: 6,
    },
    {
        id:5,
        text: "我坐起来，穿上拖鞋，站在阳台上看着楼下几乎空荡荡的街道，大家过年也都不在外面逛了。",
        music: "../音效/脚步声1.mp3",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/背景2.jpg",
        back: 3,
        next: 7,
    },
    {
        id:6,
        text: "我坐起来，穿上拖鞋，站在阳台上看着楼下几乎空荡荡的街道，大家过年也都不在外面逛了。",
        music: "../音效/脚步声1.mp3",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/背景2.jpg",
        back: 5,
        next: 7,
    },
    {
        id:7,
        text: "回到卧室，我随便从书架上取下来一本从没翻开看过的书，想着以此打发时间。",
        music: "../音效/咔哒.mp3",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/背景1.png",
        back: 6,
        next: 8,
    },
    {
        id:8,
        text: "这本书谁写的啊？嗯......作者也不认识，算了随便读读，封面设计得还挺好看的",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/背景1.png",
        back: 7,
        next: 9,
    },
    {
        id:9,
        text: "我随便翻到了一页，看到上面写着：",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/背景1.png",
        back: 8,
        next: 10,
    },
    {
        id:10,
        text: "“熔炼车间的火焰扭曲着，挣扎着，好像从地狱深处爬出的恶灵，舔舐着一切，在昏暗的车间里投射出模糊而诡异的光影。整个车间里回荡着低沉的轰鸣和钢铁在高温中挣扎的声音，仿佛是在为那些被烧灼的物体举办一场无声的葬礼”。",
        music: "../音效/恐怖氛围的音乐.m4a",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/背景1.png",
        back: 9,
        next: 11,
    },
    {
        id:11,
        text: "看起来还有点意思，不妨读一读......",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/背景1.png",
        back: 10,
        next: 12,//开头穿越
    },
    {
        id:12,
        text: "这是哪里？",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片2.jpg",
        back: 11,
        next: 13,
    },
    {
        id:13,
        text: "清醒过来后，我趴在一片室外的空地上，我赶忙爬了起来，满脸的土，一副掏煤样儿，环顾四周。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片2.jpg",
        back: 12,
        next: 14,
    },
    {
        id:14,
        text: "我看这建筑风格不像是家附近，还有几个穿着天蓝色制服、戴着肩牌的人走在路上，我望了望附近，那边的三层楼上写着，“铁南区锅炉总厂”。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片2.jpg",
        back: 13,
        next: 15,
    },
    {
        id:15,
        text: "诶！这不是父亲年轻的时候工作的地方",
        music: "../音效/砰.MP3",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片2.jpg",
        back: 14,
        next: 16,
    },{
        id:16,
        text: "养父母曾经跟我说过，我父亲在我农历一周岁生日的时候死了，我母亲让人把我带到外地找人养大，那时候人赚钱都比较费力，辗转几次到我现在的养父母，才得以有地方收留。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片2.jpg",
        back: 15,
        next: 17,
    },{
        id:17,
        text: "我还记得，我父亲应该是什么什么主任，具体的记不清了，反正还是有一定地位的。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片2.jpg",
        back: 16,
        next: 18,
    },{
        id:18,
        text: "想着想着，我突然意识到，我好像不完全是在现实生活中，因为周围的一切在我眼睛里看着好像饱和度要低一点。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片2.jpg",
        back: 17,
        next: 19,
    },{
        id:19,
        text: "这到底在哪里？",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片2.jpg",
        back: 18,
        next: 20,
    },{
        id:20,
        text: "这时候广播响了起来，“11月7日晚上18：00文化宫放映《阳光灿烂的日子》，11月7日晚上18：00文化宫放映《阳光灿烂的日子》......”",
        music: "../音效/砰.MP3",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片2.jpg",
        back: 19,
        next: 21,
    },{
        id:21,
        text: "好奇怪，现在明明2月份，这都哪跟哪啊，",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片2.jpg",
        back: 20,
        next: 22,
    },{
        id:22,
        text: "这时候又有一个旁边穿制服的人走过，黝黑的，衣服上沾了点油污，看着也像四十多岁，我选择：",
        music: "../音效/脚步声1.MP3",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片2.jpg",
        back: 21,
        next: 23,
    },{
        id:23,
        text: " ",
        name: "",
        saylihui: "",
        backlihui: "",
        option: [{
            text: "叫住他问问",
            next: 24,
        }, {
            text: "自己去四处逛逛",
            next: 28,
        },],
        background: "素材/背景/图片2.jpg",
        back: 22,
    },{
        id:24,
        text: "大兄弟，刚说11月7号放电影，这不才2月份。",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片2.jpg",
        back: 23,
        next: 25,
    },{
        id:25,
        text: "那个人匪夷所思地看着我，",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片2.jpg",
        back: 24,
        next: 26,
    },{
        id:26,
        text: "你没事吧，11月7号不就三天后。",
        name:"路人：",
        saylihui: "../picture/角色补充/222.png",
        backlihui: "",
        background: "素材/背景/图片2.jpg",
        back: 25,
        next: 27,
    },{
        id:27,
        text: "说着他就走了，也许他现在不想跟人多说话。",
        music: "../音效/脚步声1.MP3",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片2.jpg",
        back: 26,
        next: 28,
    },{
        id:28,
        text: "我往最近的一栋建筑里面走，建筑上面挂了一个很大的白底红字的板子，写着“把企业产品的质量提高到一个新的水平”。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 27,
        next: 29,
    },{
        id:29,
        text: "走近了，大门旁边还有个竖着的牌子，上面写着“设计科”。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 28,
        next: 30,
    },{
        id:30,
        text: "我走进去，绕几个弯来到一间挺大的房间，吊顶得有六米多，一排一排摆着桌子椅子，房间四周的墙壁上挂着一些很大的图纸，一些人坐在桌子前写着什么东西，还有的三三两两在图纸前面讨论着什么。",
        music: "../音效/开门声.MP3",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 29,
        next: 31,
    },{
        id:31,
        text: "有个人叫住了我。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 30,
        next: 32,
    },{
        id:32,
        text: "兄弟，新来的吗？",
        name:"路人：",
        saylihui: "../picture/角色补充/222.png",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 31,
        next: 33,
    },{
        id:33,
        text: "啊——是......",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 32,
        next: 34,
    },{
        id:34,
        text: "我还没太想好说点什么，好在那个人又说，",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 33,
        next: 35,
    },{
        id:35,
        text: "你这打扮也太奇怪了，在厂里怎么还穿成这样，哪儿来的衣服。",
        name:"路人：",
        saylihui: "../picture/角色补充/222.png",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 34,
        next: 36,
    },{
        id:36,
        text: "我突然想起来，自己的装束还停留在2024年",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 35,
        next: 37,
    },{
        id:37,
        text: "我那制服被我搞破洞了，没的穿了。",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 36,
        next: 38,
    },{
        id:38,
        text: "真是啥也不知道，门口旁边那个小屋子里还有一些备用衣服，回头拿一件换上。你这样儿怎么就来这里干活了。",
        name:"路人：",
        saylihui: "../picture/角色补充/222.png",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 37,
        next: 39,
    },{
        id:39,
        text: "原先个不在这里，我认识那谁，介绍一下就调过来了",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 38,
        next: 40,
    },{
        id:40,
        text: "唉说实在的，来这儿干嘛？搁外头做点小本买卖都比这儿强，前些个儿日子的工资又没发，我家那小孩儿还想让我给买架钢琴，我上哪儿找那么多钱。",
        name:"路人：",
        saylihui: "../picture/角色补充/222.png",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 39,
        next: 41,
    },{
        id:41,
        text: "唉，是啊，这日子不好过。我先去换个衣服。",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 40,
        next: 42,
    },{
        id:42,
        text: "说着，我就往外走了，在我没有搞清楚到底发生了什么之前，我有点不知道应该说什么。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 41,
        next: 43,
    },{
        id:43,
        text: "果然，门口有一间单独的小房间，靠门有一个柜子，里面挂着一点洗好的衣服，再往里走是一个个隔间，估计是换衣服的。",
        music: "../音效/脚步声2.MP3",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 42,
        next: 44,
    },{
        id:44,
        text: "这时候我看见墙上挂了一个很大的日历，上面写着：1998年11月4日，农历九月十六。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 43,
        next: 45,
    },{
        id:45,
        text: "奥——怪不得，所以说我穿越回了1998年。",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 44,
        next: 46,
    },{
        id:46,
        text: "诶等一下，按这个时间算，我父亲是在我一周岁生日的时候去世的，我的生日是农历九月初七。那我父亲岂不是就在一两个礼拜前......",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 45,
        next: 47,
    },{
        id:47,
        text: "我边想着父亲，边取了衣服往里走去换衣服。这时，我的思绪被隔间外的对话声打断。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 46,
        next: 48,
    },{
        id:48,
        text: "唉你听说了吗，老李头和强哥死了。就死在三号车间里面，那地方现在都被封了。",
        name: "路人1",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 47,
        next: 49,
    },{
        id:49,
        text: "啊？怪不得，我们那岗上调来几个三车间的，具体怎么死的啊。",
        name: "路人2",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 48,
        next: 50,
    },{
        id:50,
        text: "谁知道，厂里把这事儿瞒得严着呢。",
        name: "路人1",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 49,
        next: 51,
    },{
        id:51,
        text: "奥对，那个赵诠，就那个主任，在那之后几天内也都死了，那主任办公室也被封了。不知道这些事情之间有啥关系没",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 50,
        next: 52,
    },{
        id:52,
        text: "赵诠？就那个办公室在总楼二层那个，那家不挺阔的吗，那层上了楼梯右手边那片全是他办公室，就不知道为啥还只是个主任。",
        music: "../音效/砰.MP3",
        name: "路人2",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 51,
        next: 53,
    },{
        id:53,
        text: "害，谁知道，树大招风嘛。赵诠那人属实杂碎，孩子他妈据说是个外地来的医生，赵诠天天管着她，也不让她出去见人，赵诠死了，她就把孩子送到外地了，苦了孩子了，生下来还没咋着呢，基本成了孤儿了。",
        name: "路人1",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 52,
        next: 54,
    },{
        id:54,
        text: "对对，是这样，我还听说那赵诠自己还在外面找情妇呢，真不是东西。",
        name: "路人2",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 53,
        next: 55,
    },{
        id:55,
        text: "我感到后背一凉，一个主任刚刚死了，妻子是个医生，孩子送到外地，也许，他们说的就是我的父母......",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 54,
        next: 56,
    },{
        id:56,
        text: "老李头和强哥，这都是谁，这跟父亲的死有关系吗",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 55,
        next: 57,
    },{
        id:57,
        text: "现在我也理不清楚到底发生了什么，我认真想着这几个小时经历的一切。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 56,
        next: 58,
    },{
        id:58,
        text: "我从小到大都没人告诉我父母是怎么死的，趁现在这个机会一定要弄清楚......",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片3.png",
        back: 57,
        next: 59,
    },{
        id:59,
        text: "就在这个晚上，去父亲办公室看一看。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片4.jpg",
        back: 58,
        next: 60,
    },{
        id:60,
        text: "办公室上贴着封条，想必已经有些时日没人来过这里了",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片4.jpg",
        back: 59,
        next: 61,
    },{
        id:61,
        text: "尝试转动门把手，发现门是紧锁着的",
        music: "../音效/转门把手(1).MP3",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片4.jpg",
        back: 60,
        next: 62,
    },{
        id:62,
        text: "尝试了几次后仍然无法打开",
        music: "../音效/转门把手(1).MP3",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片4.jpg",
        back: 61,
        next: 63,
    },
    {
        id:63,
        text: "看来是无法直接打开了，保卫科应该有这里的钥匙，先去保卫科吧",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片4.jpg",
        back: 62,
        next: 64,
    },{
        id:64,
        text: "保卫科亮着昏暗的灯光，桌上散落着一些报纸，还有一杯隐约冒着丝丝热气的茶水",
        music: "../音效/恐怖氛围的音乐.m4a",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片5.jpg",
        back: 63,
        next: 65,
    },{
        id:65,
        text: "似乎有人还在上班，但四周不见踪影",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片5.jpg",
        back: 64,
        next: 66,
    },{
        id:66,
        text: "先找找钥匙吧，好像是挂在墙上",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片5.jpg",
        back: 65,
        next: 67,
    },{
        id:67,
        text: "找到了，这把就是父亲办公室的钥匙",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片5.jpg",
        back: 66,
        next: 68,
    },{
        id:68,
        text: "回到门口，将钥匙插入锁孔中，转动门把手",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片4.jpg",
        back: 67,
        next: 69,
    },{
        id:69,
        text: "‘咔嚓’",
        music: "../音效/开门声.MP3",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片4.jpg",
        back: 68,
        next: 70,
    },{
        id:70,
        text: "我能听到我心脏怦怦跳的声音，这是我从未来过的地方，这里面死去了我那几乎可以说是素未谋面的父亲......我推门进入了房间。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片7.jpg",
        back: 69,
        next: 71,
    },{
        id:71,
        text: "打开灯后发现这个房间似乎有哪里不对劲，好像有被人翻动过的痕迹",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片7.jpg",
        back: 70,
        next: 72,
    },{
        id:72,
        text: "先在这里仔细找找有什么线索吧",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片7.jpg",
        back: 71,
        next: 73,
    },{
        id:73,
        text: "来到桌旁，桌子上有一副破碎的相片",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 72,
        next: 74,
    },{
        id:74,
        text: "相片？是谁打碎成这样的呢？",
        music: "../音效/砰.MP3",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 73,
        next: 75,
    },{
        id:75,//游戏1
        text: "我走近相片观察，动手拼了起来",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 74,
        next: 76,
    },{
        id:76,
        text: "这难道就是我的父母吗......",
        music: "../音效/《志铭》犬儒乐队.MP3",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 75,
        next: 77,
    },{
        id:77,
        text: "我小心翼翼地抚摸着照片，好像在想象着自己可以碰到他们。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 76,
        next: 78,
    },{
        id:78,
        text: "那个男人很高大，穿着西服打着领带，他的眼睛——他的眼睛长得和我一模一样。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 77,
        next: 79,
    },{
        id:79,
        text: "站在他旁边的那个女人，非常美丽，有着乌黑柔顺的头发，眉毛化得十分精细......",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 78,
        next: 80,
    },{
        id:80,
        text: "妈？爸？",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 79,
        next: 81,
    },{
        id:81,
        text: "我正在望着我的家人，这是我有生以来的第一次。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 80,
        next: 82,
    },{
        id:82,
        text: "我感觉我的内心出现一阵强烈的剧痛。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 81,
        next: 83,
    },{
        id:83,
        text: "为什么你们要离开我？为什么要把我送到外地？",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 82,
        next: 84,
    },{
        id:84,
        text: "照片背后好像写着些什么？",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 83,
        next: 85,
    },{
        id:85,
        text: "相片的背面写着铁南区三月路7号",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 84,
        next: 86,
    },{
        id:86,
        text: "这是......我爸妈家的住址？",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 85,
        next: 87,
    },{
        id:87,
        text: "我仔细地把照片收起来，转眼看到桌上有一本日志",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 86,
        next: 88,
    },{
        id:88,
        text: "机房日志......",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 87,
        next: 89,
    },{
        id:89,
        text: "",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 88,
        next: 90,
    },{
        id:90,
        text: "看不到24日之后的记录......",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 89,
        next: 91,
    },{
        id:91,
        text: "我想起早上从工友那里听到的对话",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 90,
        next: 92,
    },{
        id:92,
        text: "难道三号车间发生的事和父亲的死有关联？......",
        music: "../音效/砰.MP3",    
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 91,
        next: 93,
    },{
        id:93,
        text: "我的父亲怎么可能会牵扯到命案中......",    
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 92,
        next: 94,
    },{
        id:94,
        text: "这时楼道里传来一阵沉重而诡异的脚步声",
        music: "../音效/脚步声1.MP3",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 93,
        next: 95,
    },{
        id:95,
        text: " ",
        name: "",
        option:[{
            text:"感觉不对劲，先行撤离",
            next:96,
        },{
            text:"去三号车间探索",
            next:99,
        }],
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 94,
    },{
        id:96,
        text: "感觉不对劲，先行撤离",
        music: "../音效/恐怖氛围的音乐.m4a",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片8.jpg",
        back: 95,
        next: 97,
    },{
        id:97,
        text: "趁脚步声还没接近，我迅速从楼道另一头的楼梯下楼，离开了工厂",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片4.jpg",
        back: 96,
        next: 98,
    },{
        id:98,
        text: "明早去一趟相片上的地址吧，我母亲......我母亲会住在那里吗？",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片4.jpg",
        back: 97,
        next: 122,
    },{
        id:99,
        text: "去三号车间探索",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片9.jpg",
        back: 98,
        next: 100,
    },{
        id:100,
        text: "离开办公室，朝三号车间方向走去",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片9.jpg",
        back: 99,
        next: 101,
    },{
        id:101,
        text: "刚走没几步就听到身后传来一声喊叫",
        music: "../音效/砰.MP3",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片9.jpg",
        back: 100,
        next: 102,
    },{
        id:102,
        text: "干什么的！这么晚了还在工厂里！",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片9.jpg",
        back: 101,
        next: 103,
    },{
        id:103,
        text: "这一声让我瞬间感到毛骨悚然",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片9.jpg",
        back: 102,
        next: 104,
    },{
        id:104,
        text: "我缓慢地回头，发现那人是工厂的一个保安",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片9.jpg",
        back: 103,
        next: 105,
    },{
        id:105,
        text: "原来是保安啊.....",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片9.jpg",
        back: 104,
        next: 106,
    },{
        id:106,
        text: "心中的恐惧消散了不少",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片9.jpg",
        back: 105,
        next: 107,
    },{
        id:107,
        text: "你是谁？鬼鬼祟祟的在干什么？",
        name: "保安",
        saylihui: "素材/立绘/保安.png",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片9.jpg",
        back: 106,
        next: 108,
    },{
        id:108,
        text: "保安大哥，我是这工厂原先主任的好友。我觉得他的死有蹊跷，想来这里找找有什么线索，你对他的死知道些什么吗？",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片9.jpg",
        back: 107,
        next: 109,
    },{
        id:109,
        text: "原来是这样......",
        name: "保安",
        saylihui: "素材/立绘/保安.png",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片9.jpg",
        back: 108,
        next: 110,
    },{
        id:110,
        text: "跟我去个地方吧，或许能帮到你找些线索",
        name: "保安",
        saylihui: "素材/立绘/保安.png",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片9.jpg",
        back: 109,
        next: 111,
    },{
        id:111,
        text: "真的吗！太感谢您了。",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片9.jpg",
        back: 110,
        next: 112,
    },{
        id:112,
        text: "跟着保安的步伐，穿过工厂长长的走廊，又经过了不知几个弯弯绕绕的拐角",
        music: "../音效/脚步声2.MP3",
        name: "",
        saylihui: "",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片9.jpg",
        back: 111,
        next: 113,
    },{
        id:113,
        text: "最后来到了工厂偏僻一角的一个房间",
        name: "",
        saylihui: "",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片10.jpg",
        back: 112,
        next: 114,
    },{
        id:114,
        text: "进去吧，里面有你想找的东西",
        name: "保安",
        saylihui: "素材/立绘/保安.png",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片10.jpg",
        back: 113,
        next: 115,
    },{
        id:115,
        text: "走进房间，里面一片昏暗，伸手不见五指",
        music: "../音效/开门声.MP3",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片10.jpg",
        back: 114,
        next: 117,
    },{
        id:117,
        text: "‘砰’",
        music: "../音效/砰.MP3",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片10.jpg",
        back: 115,
        next: 118,
    },{
        id:118,
        text: "我感觉脑袋突然遭受某种钝器的重击，一下子倒在地上，意识渐渐模糊......",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片10.jpg",
        back: 117,
        next: 119,
    },{
        id:119,
        text: "隐约听到身后传来话语",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片10.jpg",
        back: 118,
        next: 120,
    },{
        id:120,
        text: "你真以为你能揭开真相吗？那个人死于他该遭受的惩罚",
        name: "保安",
        saylihui: "素材/立绘/保安.png",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片10.jpg",
        back: 119,
        next: 120,
    },{
        id:121,
        text: "我的呼吸逐渐微弱，整个工厂再次陷入沉寂，只有墙壁上的阴影缓缓变动，仿佛在默默见证着这一切。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片10.jpg",
        back: 120,
        next: 300,  //坏结局
    },{
        id:122,
        text: "第二天，我来到了相片上说的地方，观察了一会，我叫住了一个看起来比较面善的大娘。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 98,
        next: 123,
    },{
        id:123,
        text: "请问这家是有个女人住着吧。",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 122,
        next: 124,
    },{
        id:124,
        text: "“诶呦，你找她做什么，”大娘皱着眉头一脸正经地小声说，“那家刚死了人。”",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 123,
        next: 125,
    },{
        id:125,
        text: "我点了点头，待大娘走了之后，我刚准备敲门，又愣住了。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 124,
        next: 126,
    },{
        id:126,
        text: "开门之后，那，那可是我的母亲啊，是吗？是吧，冥冥之中我似乎能够确认那就是我的母亲，这一切十分得不真实，好吧本来就不是真实的，但是在此之前，我似乎没有真正地感知到这一切",
        music: "../音效/咔哒.MP3",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 125,
        next: 127,
    },{
        id:127,
        text: "我的心突突地跳着。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 126,
        next: 128,
    },{
        id:128,
        text: "后来我都不知道，我是哪一秒抬起手来，准备敲门。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 127,
        next: 129,
    },{
        id:129,
        text: "正准备敲，我听见里面隐约的有两个人交流的声音，小得听不出是谁在说话。",
        name: "A",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 128,
        next: 130,
    },{
        id:130,
        text: "你为什么要这样？这一切都是我做的。",
        music: "../音效/《志铭》犬儒乐队.MP3",
        name: "B",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 129,
        next: 131,
    },{
        id:131,
        text: "因为你太苦了，你都被他折磨了这么多年，你还不曾体验过美好的日子，而且你进去之后，我要凭着什么才想要生活下去......",
        name: "A",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 130,
        next: 132,
    },{
        id:132,
        text: "不，我已经体验过大部分事情了，况且我不能再生育了，我也没什么好留恋的......",
        name: "B",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 131,
        next: 133,
    },{
        id:133,
        text: "后面的说话声音太小，听不见了，我先躲了起来，但过了半晌还不见有人进出，于是我犹豫了片刻过后前去敲门。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 132,
        next: 134,
    },{
        id:134,
        text: "开门的只见一个三十岁左右的女人，瘦瘦的，手腕上有几道旧伤疤，面色有点苍白发着黄，看起来不怎么外出做活，黑眼袋挺重的，但仍可以从那憔悴的面容下看出她原本美丽的容颜。",
        music: "../音效/咔哒.MP3",
        name: "",
        saylihui: "",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 133,
        next: 135,
    },{
        id:135,
        text: "我，我是便衣警察，厂子最近出了点案子，不知道您知不知道。",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 134,
        next: 136,
    },{
        id:136,
        text: "面前这可是我的母亲，可是我几乎和她同岁，我又如何告诉她我的真实身份呢？我又会何时离开这个时空？我们以后还会见面吗？",
        name: "",
        saylihui: "",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 135,
        next: 137,
    },{
        id:137,
        text: "之前已经有警察来过了，我真的什么也不清楚。",
        name: "母亲",
        saylihui: "素材/立绘/母亲.png",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 136,
        next: 138,
    },{
        id:138,
        text: "我知道你跟一个姓赵的主任认识，你跟他什么关系，据我所知那个男人前两天没了。",
        music: "../音效/砰.MP3",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 137,
        next: 139,
    },{
        id:139,
        text: "看起来她的警惕心提高了",
        name: "",
        saylihui: "",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 138,
        next: 140,
    },{
        id:140,
        text: "嗯......我是她的妻子，我讲过了我比任何人都想知道发生了什么......厂里面也没给一个负责人的解释，他是死在厂里的，我......",
        music: "../音效/《志铭》犬儒乐队.MP3",
        name: "母亲",
        saylihui: "素材/立绘/母亲.png",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 139,
        next: 141,
    },{
        id:141,
        text: "她说不下去了，站在那里，她也没有哭，她似乎已经木了。",
        name: "",
        saylihui: "",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 140,
        next: 142,
    },{
        id:142,
        text: "我强打着精神，这一两天经历的事情对我来说冲击太大了。",
        name: "",
        saylihui: "",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 141,
        next: 143,
    },{
        id:143,
        text: "你还了解他什么？他生前和谁有过矛盾吗？",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 142,
        next: 144,
    },{
        id:144,
        text: "我不了解，他不经常跟我说这些。不过他还为工厂购置了新设备，为工厂着想，应该 不会有什么矛盾吧。",
        name: "母亲",
        saylihui: "素材/立绘/母亲.png",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 143,
        next: 145,
    },{
        id:145,
        text: "您抽不抽烟？",
        name: "母亲",
        saylihui: "素材/立绘/母亲.png",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 144,
        next: 146,
    },{
        id:146,
        text: "说着她把烟送到了我面前，我看了一眼，是个大牌子。",
        name: "",
        saylihui: "",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 145,
        next: 147,
    },{
        id:147,
        text: "不好意思，我不抽烟。",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 146,
        next: 148,
    },{
        id:148,
        text: "害，这玩意儿抽着上瘾。",
        name: "母亲",
        saylihui: "素材/立绘/母亲.png",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 147,
        next: 149,
    },{
        id:149,
        text: "说着她点上了一支烟。",
        name: "",
        saylihui: "",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 148,
        next: 150,
    },{
        id:150,
        text: "我好想说，妈，您不能这样子抽烟，这对身体不好......",
        name: "",
        saylihui: "",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 149,
        next: 151,
    },{
        id:151,
        text: "您平常靠什么收入？",
        name: "母亲",
        saylihui: "母亲",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 150,
        next: 152,
    },{
        id:152,
        text: "曾经也想当个文艺女青年，但入行不简单，那时候穷得丁零当啷的，后来只好做了医生，也是入行了医生之后才来到这里，认识了赵主任。",
        name: "母亲",
        saylihui: "素材/立绘/母亲.png",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 151,
        next: 153,
    },{
        id:153,
        text: "我毕竟是外来的，也就三两年的功夫，对这里也没有很熟悉，能过得下去日子就行，赵主任平时也能赚不少，前些个购进那两台德国机器，也赚了好几万。",
        name: "母亲",
        saylihui: "素材/立绘/母亲.png",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 152,
        next: 154,
    },{
        id:154,
        text: "两台德国机器？",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 153,
        next: 155,
    },{
        id:155,
        text: "女人愣了一下",
        name: "",
        saylihui: "",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 154,
        next:156,
    },{
        id:156,
        text: "嗯对，我也不懂他们这机器那机器，我也不感兴趣。您还有的调查不，抽烟犯困，我得去搞点饭吃，再睡个晌午觉了。",
        name: "母亲",
        saylihui: "素材/立绘/母亲.png",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 155,
        next: 157,
    },{
        id:157,
        text: "那先这样，感谢您配合。",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "素材/立绘/母亲.png",
        background: "素材/背景/图片11.jpg",
        back: 156,
        next: 158,
    },{
        id:158,
        text: "我离开了那里。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 157,
        next: 159,
    },{
        id:159,
        text: "到最后我也不知道如何开口，去讲我们之间的关系...",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 158,
        next: 160,
    },{
        id:160,
        text: "希望......希望还可以见到她",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 159,
        next: 161,
    },{
        id:161,
        text: "德国机器，昨天还看到了机房日志，也许先查出来父亲的死因吧，这样也默默地可以给母亲一个交代",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 160,
        next: 162,
    },{
        id:162,
        text: " ",
        name: "",
        saylihui: "",
        backlihui: "",
        option:[
            {
                text:"晚上去机房调查",
                next:163
            },
        ],
        background: "素材/背景/图片11.jpg",
        back: 161,
    },{
        id:163,
        text: "晚上了，厂里静悄悄的。我来到三号车间门口,似乎有个解密游戏才能打开",
        music: "../音效/脚步声1.MP3",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片12.jpg",
        back: 162,
        next: 164,      //小游戏
    },{
        id:164,
        text: "通过游戏后，我打开了机房的大门，四周十分昏暗，还夹杂着一股铁锈的味道。我走进去，悄悄地，慢慢地，看看有没有什么奇怪的地方。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片13.jpg",
        back: 163,
        next: 165,
    },{
        id:165,
        text: "这两台机器好像有点与众不同......看着这金属挺新的，构造也挺复杂",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片13.jpg",
        back: 164,
        next: 166,
    },{
        id:166,
        text: "等等！这是什么",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片13.jpg",
        back: 165,
        next: 167,
    },{
        id:167,
        text: "我转了转身子，直到恰好可以借着月光看清楚。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片13.jpg",
        back: 166,
        next: 168,
    },{
        id:168,
        text: "血？",
        music: "../音效/砰.MP3",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片13.jpg",
        back: 167,
        next: 169,
    },{
        id:169,
        text: "面积不是很大，看起来有些是喷溅上去的，血已经干了，颜色深得近乎黑色。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片13.jpg",
        back: 168,
        next: 170,
    },{
        id:170,
        text: "果然，那两个可怜的的工人应该就是在这毙命的。那......他们的死，岂不是父亲导致的？",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片13.jpg",
        back: 169,
        next: 171,
    },{
        id:171,
        text: "还没来得及多想，突然，一阵诡异的脚步声传来——“哒，哒，哒哒哒哒......”我猛然向机房的大门看去，只见黑暗中缓缓出现一双凌厉的眼睛，正恶狠狠地盯着我。",
        music: "../音效/脚步声2.MP3",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片13.jpg",
        back: 170,
        next: 172,
    },{
        id:172,
        text: "你是什么人？怎么敢在这个鬼地方待着？",
        music: "../音效/恐怖氛围的音乐.m4a",
        name: "保安",
        saylihui: "素材/立绘/保安.png",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片13.jpg",
        back: 171,
        next: 173,
    },{
        id:173,
        text: "保安用略显兴奋的声音询问着我。",
        name: "",
        saylihui: "",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片13.jpg",
        back: 172,
        next: 174,
    },{
        id:174,
        text: "我，我——我就是好奇，听他们说老李头和强哥死了，我想知道是不是真的，以及赵主任怎么会那么巧在他们死后不久就突然身亡......",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片13.jpg",
        back: 173,
        next: 175,
    },{
        id:175,
        text: "我的声音越来越小。",
        name: "",
        saylihui: "",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片13.jpg",
        back: 174,
        next: 176,
    },{
        id:176,
        text: "赵主任？哼，他也配！人模狗样的东西。还想开除我，那我就先弄死他！",
        name: "保安",
        saylihui: "素材/立绘/保安.png",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片13.jpg",
        back: 175,
        next: 177,
    },{
        id:177,
        text: "你说什么？",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片13.jpg",
        back: 176,
        next: 178,
    },{
        id:178,
        text: "我感到很惊讶，惊讶之余还有点疑惑，这个保安听声音似乎年龄不是很大，他的用词透着和年龄不相符的凶狠和成熟。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片13.jpg",
        back: 177,
        next: 179,
    },{
        id:179,
        text: "“呵呵，我开玩笑呢，杀他我还嫌脏了手。”保安干笑了两声，却让我浑身发麻，我感到很不对劲",
        name: "保安",
        saylihui: "素材/立绘/保安.png",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片13.jpg",
        back: 178,
        next: 180,
    },{
        id:180,
        text: "啊，这里挺吓人的，我先走了，您忙......",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片13.jpg",
        back: 179,
        next: 181,
    },{
        id:181,
        text: "我边说边往出走，最后越来越快，在保安的注视下，我快速离开了这里。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片13.jpg",
        back: 180,
        next: 182,
    },{
        id:182,
        text: "第二天起来，我复盘着之前发生的一切。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片2.jpg",
        back: 181,
        next: 183,
    },{
        id:183,
        text: "父亲，德国机器，死了两个工人，恶狠狠的保安。为什么那个保安对我如此之凶，他又不认识我。我并没有很清晰的头绪，于是决定去打听打听有关那个保安的事情。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片2.jpg",
        back: 182,
        next: 184,
    },{
        id:184,
        text: "我出了门，上午的时候在厂子内逛了逛。一晃到了中午，我穿着工厂的制服来到了饭堂，四处走走，这时我听到了似乎有人在悄悄聊着前两天命案的事情",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 183,
        next: 185,
    },{
        id:185,
        text: "上面没调查那个保安......",
        name: "工友A",
        saylihui: "../picture/角色补充/333.png",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 184,
        next: 186,
    },{
        id:186,
        text: "我环顾了一下，去最近的打饭的地方盛了烧茄子和猪肉炖粉条，又盛了一碗水捞饭，回到了刚才工友吃饭的地方。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 185,
        next: 187,
    },{
        id:187,
        text: "兄弟们好哇，我是新来的，能一块吃不？",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 186,
        next: 188,
    },{
        id:188,
        text: "坐坐坐",
        name: "工友",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 187,
        next: 189,
    },{
        id:189,
        text: "工友们看起来都很疲惫，但都热情地招待了我。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 188,
        next: 190,
    },{
        id:190,
        text: "最近厂里是不是发生了点事情，我前几天听别的工友说，有个保安最近挺古怪的，脾气特别暴。",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 189,
        next: 191,
    },{
        id:191,
        text: "唉这新来的都知道了，上头那些人肯定是装聋作哑，这么说吧，具体我们也不知道发生了啥，就知道那个保安和没的那两个工友关系挺好的，空闲时间经常一起喝酒打牌之类的",
        name: "工友A",
        saylihui: "../picture/角色补充/333.png",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 190,
        next: 192,
    },{
        id:192,
        text: "我也听说了，这一下子好兄弟没了，痛啊。何况那两个没的应该是操作机器时搞错了，那机器还是那个主任，姓什么来着，对对赵主任买的，也是他指挥着操作的。",
        name: "工友B",
        saylihui: "../picture/角色补充/444.png",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 191,
        next: 193,
    },{
        id:193,
        text: "赵主任？就那个前两天也死了的那个？",
        name: "工友A",
        saylihui: "../picture/角色补充/333.png",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 192,
        next: 194,
    },{
        id:194,
        text: "对对对就那个，最近发生的事情太多了。",
        name: "工友B",
        saylihui: "../picture/角色补充/444.png",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 193,
        next: 195,
    },{
        id:195,
        text: "现在这生活不好过啊，谁都绷着弦儿，我姐在财会科，说是最近工厂最近也亏损得严重。",
        name: "工友A",
        saylihui: "../picture/角色补充/333.png",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 194,
        next: 196,
    },{
        id:196,
        text: "是啊，奥对，我还听说那个保安本来就跟赵主任关系不好，好像是因为赵主任为了节省开始减少亏损，计划着把那个保安裁了，但保安本来也没有其他的赚钱的法子，说了半天，反正不是很合。",
        name: "工友B",
        saylihui: "../picture/角色补充/444.png",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 195,
        next: 197,
    },{
        id:197,
        text: "唉，太复杂了。",
        name: "工友A",
        saylihui: "../picture/角色补充/333.png",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 196,
        next: 198,
    },{
        id:198,
        text: "感觉似乎工人们对父亲的评价并不是很好，怎么会这样......",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 197,
        next: 199,
    },{
        id:199,
        text: "我......我母亲还说父亲弄来的两台德国机器，平白无故赚了好几万，而工人们的工资还在拖欠......",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 198,
        next: 200,
    },{
        id:200,
        text: "还是先弄清楚真相吧，现在还不知道保安到底是个什么样子的人",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 199,
        next: 201,
    },{
        id:201,
        text: "保安和我父亲关系不好，和那两名工伤去世的工友关系很好......那......",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 200,
        next: 202,
    },{
        id:202,
        text: " ",
        name: "",
        option:[
            {
                text:"晚上去保安房间查看",
                next:203,
            },{
                text:"在饭桌上进一步询问保安相关",
                next:214,
            },
        ],
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 201,
    },{
        id:203,
        text: "说着说着，大家也都吃完了，把吃得干干净净的餐盘拿到了回收处，便各自散了。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 202,
        next: 204,
    },{
        id:204,
        text: "到了晚上，我来到了保安房间。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片15.png",
        back: 203,
        next: 205,
    },{
        id:205,
        text: "我打量着两眼面前这个逼仄的小房间，便走了进去。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片15.png",
        back: 204,
        next: 206,
    },{
        id:206,
        text: "只见屋子里并没有什么陈设，只有一张不知用了多久的床和一张木桌。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片15.png",
        back: 205,
        next: 207,
    },{
        id:207,
        text: "我走到木桌旁打算看看有什么蛛丝马迹。只见上面放着一张大日历，上面还有一些涂画标记，窗户被风吹开了，我刚想过去关窗户，突然听见什么悉悉索索的声音，我抖了一下。一只耗子从床下钻了出来。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片16.png",
        back: 206,
        next: 208,
    },{
        id:208,
        text: "原来是耗子.....",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片16.png",
        back: 207,
        next: 209,
    },{
        id:209,
        text: "再在床底下找一找吧......",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片16.png",
        back: 208,
        next: 210,
    },{
        id:210,
        text: "",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片16.png",
        back: 209,
        next: 211,
    },{
        id:211,
        text: "别动！",
        name: "保安",
        saylihui: "素材/立绘/保安.png",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片16.png",
        back: 210,
        next: 212,
    },{
        id:212,
        text: "还没等我拿出箱子里的东西，一声熟悉而又陌生的声音，没错，保安回来了。",
        name: "",
        saylihui: "",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片16.png",
        back: 211,
        next: 212,
    },{
        id:213,
        text: "还未等我反应过来，保安就抡起巡逻用的警棍......",
        name: "",
        saylihui: "",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片16.png",
        back: 212,
        next: 300,//坏结局
    },{
        id:214,
        text: "保安平日里都负责什么呢？感觉保安的工作还挺重要的，怎么会说开除就能开除呢？",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片17.png",
        back: 202,
        next: 215,
    },{
        id:215,
        text: "我趁着工友们说话的间隙问道。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片17.png",
        back: 214,
        next: 216,
    },{
        id:216,
        text: "主要就是负责检查人员进出，当然还会有些巡逻，我记得，尤其晚上九点到十一点，这期间的巡逻很重要。",
        name: "工友",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片17.png",
        back: 215,
        next: 217,
    },{
        id:217,
        text: "奥，感觉工作确实挺重要的。",
        name: "我 ",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片17.png",
        back: 216,
        next: 218,
    },{
        id:218,
        text: "饭桌上工友们你一句我一句地说着，不知不觉到了下午开工时间，于是大家各自回到岗位。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片17.png",
        back: 217,
        next: 219,
    },{
        id:219,
        text: "晚上九点十分的时候，我来到了保安的房间，小心翼翼地观察着四周。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片18.png",
        back: 218,
        next: 220,
    },{
        id:220,
        text: "房间的面积并不大，大概只有十平方米，墙壁是浅灰色的粉刷，略显斑驳，地面铺着旧式水泥地板。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片18.png",
        back: 219,
        next: 221,
    },{
        id:221,
        text: "房间里摆放着一张单人床，床边有一张小桌子，上面放着对讲机、电筒、一支笔和几个本子，本子都还挺厚的，看起来尽职尽责的。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片18.png",
        back: 220,
        next: 222,
    },{
        id:222,
        text: "我随便看了一本封皮是黑色的，里面是保安记的日志，封面上写着保安的名字，张勇齐。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片18.png",
        back: 221,
        next: 223,
    },{
        id:223,
        text: "墙角处还摆了一个的暖壶，旁边放着两个搪瓷杯。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片18.png",
        back: 222,
        next: 224,
    },{
        id:224,
        text: "这房间东西并不多，再仔细看看吧",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片18.png",
        back: 223,
        next: 225,
    },{
        id:225,
        text: "我俯下身子，看看床底下有些什么",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片18.png",
        back: 224,
        next: 226,
    },{
        id:226,
        text: "",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片18.png",
        back: 225,
        next: 227,
    },{
        id:227,
        text: "我把衣服从箱子里拿了出来。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片18.png",
        back: 226,
        next: 228,
    },{
        id:228,
        text: "有点像21世纪那种登山时候背的保温毯，就是厚了好多，结实了好多，材质也不是完全相同",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片18.png",
        back: 227,
        next: 229,
    },{
        id:229,
        text: "我慢慢地把它展开，突然心头一紧，这件衣服的一侧沾满了血，也都干了。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片18.png",
        back: 228,
        next: 230,
    },{
        id:230,
        text: "我隐约地不安起来",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片18.png",
        back: 229,
        next: 231,
    },{
        id:231,
        text: "也许......也许这个血就是父亲的......",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片18.png",
        back: 230,
        next: 232,
    },{
        id:232,
        text: "我把这件东西带走了。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片18.png",
        back: 231,
        next: 233,
    },{
        id:233,
        text: "早上起来，我来到了警察局，把昨晚拿到的防护服递交给了警察，小心翼翼地以免破坏破坏任何一点痕迹。经过一番核验和进一步调查，警方确定保安为此案凶手，并给出了两位工友之死和父亲之死整个事情的完整还原。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片19.png",
        back: 232,
        next: 234,
    },{
        id:234,
        text: "父亲购置了两台德国机器吃回扣，赚了一笔钱，但是父亲并不会操作，在指挥失误后两个工人因工而死，工友的好兄弟，保安，在个人矛盾加之下，于九月初七晚上吃完饭在办公室里面杀害了赵诠，身穿防护服将尸体拖到熔炼车间焚化。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片19.png",
        back: 233,
        next: 235,
    },{
        id:235,
        text: "警方逮捕了保安，在这个过程中我争取到了一个和保安对话的机会。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片19.png",
        back: 234,
        next: 236,
    },{
        id:236,
        text: "你为什么要害死他？",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片19.png",
        back: 235,
        next: 237,
    },{
        id:237,
        text: "为什么？这个世界哪来那么多道理可讲！你知道吗，我从不求富贵，过上还算可以的日子对我有多么重要，我知道公平还在这个社会，我就还能支棱着活下去，可是我的好兄弟死了，上面也没人管，钱都让有权力的人拿了去，还要把我赶出工厂，没错，我是杀了人，我有罪，可是这又如何呢？曾经我也热爱文学，曾经我写小说，曾经我昂扬向上，可是那是曾经，现在我无所谓的，全都无所谓！",
        name: "保安",
        saylihui: "素材/立绘/保安.png",
        backlihui: "素材/立绘/保安.png",
        background: "素材/背景/图片19.png",
        back: 236,
        next: 238,
    },{
        id:238,
        text: "我的父亲怎么会这样......",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片19.png",
        back: 237,
        next: 239,
    },{
        id:239,
        text: "可是......可是.....",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片19.png",
        back: 238,
        next: 240,
    },{
        id:240,
        text: "隐约中有什么东西即将破裂了，如果我没有穿越，我就不会知道这一切，我便可以活在正义之中，我便可以永远相信我的父亲是一位......",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片19.png",
        back: 239,
        next: 241,
    },{
        id:241,
        text: "保安被带走了，我愣在原地，久久没有缓过神来。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片19.png",
        back: 240,
        next: 242,
    },{
        id:242,
        text: "然而这就是全部的真相吗？",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片19.png",
        back: 241,
        next: 243,
    },{
        id:243,
        text: "我的思绪很乱，保安上午就被带走了，一整个下午我都在厂子里面漫无目的地逛游，想去找我的母亲，但却又没有理由和身份。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片19.png",
        back: 242,
        next: 244,
    },{
        id:244,
        text: "不能再这样消磨自己了，晚上文化宫不是放电影，那个《阳光灿烂的日子》吗，我去看看吧",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片19.png",
        back: 243,
        next: 245,
    },{
        id:245,
        text: "......",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 244,
        next: 246,
    },{
        id:246,
        text: "影片要结束了电影最后的几个片段画面是黑白色的，影片里面的人物坐在车上，客气地来回递酒，看着已经陌生了的城市......而我旁边的几个工友也在闲聊。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 245,
        next: 247,
    },{
        id:247,
        text: "你说，十年后我们会在哪里呢？我还会干现在这行吗？",
        name: "工友a",
        saylihui: "../picture/角色补充/333.png",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 246,
        next: 248,
    },{
        id:248,
        text: "谁说的准，我觉得不了，反正我也想去大城市看看，哪怕当个出租车司机呢，诶我说真的，我好想买辆桑塔纳......",
        name: "工友b",
        saylihui: "../picture/角色补充/444.png",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 247,
        next: 249,
    },{
        id:249,
        text: "有梦想敢情好啊，现在这世上的事，一天一个样儿，谁知道明天又会发生什么。",
        name: "工友a",
        saylihui: "../picture/角色补充/333.png",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 248,
        next: 250,
    },{
        id:250,
        text: "是啊，老老实实做个普通人得了，别偷别抢别犯事儿的，就比如那保安小张，前阵子还一块喝酒呢，那是几号来着，对初七下了工，第二天厂子放假，我俩原本说就出厂子逛逛吃个饭，哪成想在外边从傍晚聊到第二天早上，一宿没睡，他跟我说了一宿他另外那俩死去的好兄弟，可是现在好了，突然也进局子了。",
        name: "工友b",
        saylihui: "../picture/角色补充/444.png",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 249,
        next: 251,
    },{
        id:251,
        text: "唉是啊，这年头，也不是说一个人想做个善良人就能做的，放心吧，还有咱们这帮好兄弟陪着你呢，过去的事情就让它过去吧。",
        name: "工友a",
        saylihui: "../picture/角色补充/333.png",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 250,
        next: 252,
    },{
        id:252,
        text: "初七晚上？警察不是说这是父亲被害时间吗？下工大概是傍晚五点来钟，可是这样说那个保安也不可能去一趟父亲办公室啊",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 251,
        next: 253,
    },{
        id:253,
        text: "很奇怪......",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 252,
        next: 254,
    },{
        id:254,
        text: "影片彻底结束了，人们陆陆续续地往外走，我也边走边思考着。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 253,
        next: 255,
    },{
        id:255,
        text: "这到底都是怎么回事......以及我还是没有去再看看母亲，为什么她明明是我的母亲，我能记住的在她身边的时间不超过二十分钟......何以为家",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片14.png",
        back: 254,
        next: 256,
    },{
        id:256,
        text: "不知不觉间，我又快走到了保安的房间，远远地能够看见保安的房门开着，我选择",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 255,
        next: 257,
    },{
        id:257,
        text: " ",
        name: "",
        saylihui: "",
        option:[
            {
                text: "走近保安的房间再去看看",
                next:258,
            },{
                text: "去母亲住的地方找母亲",
                next:263,
            },
        ],
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 256,
    },{
        id:258,
        text: "走近保安的房间,我远远地看见一个女人从保安的房间里面走了出来，手里拿着那本我曾经看见过的写着保安名字的本子，只不过跟我翻开的不是同一本，这本是蓝色的。她似乎在本子上涂改着什么。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 257,
        next: 259,
    },{
        id:259,
        text: "走近保安的房间,我远远地看见一个女人从保安的房间里面走了出来，手里拿着那本我曾经看见过的写着保安名字的本子，只不过跟我翻开的不是同一本，这本是蓝色的。她似乎在本子上涂改着什么。",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 258,
        next: 260,
    },{
        id:260,
        text: "我好想走上前去叫住她，我不知道生命里我还有多少次和母亲说话的机会。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 259,
        next: 261,
    },{
        id:261,
        text: "母亲似乎看见了我，但她装作并不认识我，这个之前的“便衣警察”，快步走开，行色匆匆。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 260,
        next: 261,
    },{
        id:262,
        text: "我呆呆地站在原地，看着母亲的背影远去......",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 261,
        next: 269, //保安穿越
    },{
        id:263,
        text: "我决定去找母亲",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 262,
        next: 264,
    },{
        id:264,
        text: "我缓步走向母亲住的地方，就在刚刚能够看清门口上贴的快要掉了的福字的时候，我突然看见母亲正往家门口走，手里拿着那本我曾经看见过的写着保安名字的本子，只不过跟我翻开的不是同一本，这本是蓝色的。她似乎在本子上面涂改着什么。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 263,
        next: 265,
    },{
        id:265,
        text: "母亲......？",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 264,
        next: 266,
    },{
        id:266,
        text: "我好想走上前去叫住她，我不知道生命里我还有多少次和母亲说话的机会。母亲似乎看见了我，但她装作并不认识我，这个之前的“便衣警察”，加快了步子，走向门口，迅速关上了门。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 265,
        next: 267,
    },{
        id:267,
        text: "母亲似乎看见了我，但她装作并不认识我，这个之前的“便衣警察”，加快了步子，走向门口，迅速关上了门。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 266,
        next: 267,
    },{
        id:268,
        text: "这是我最后一次见到母亲。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片11.jpg",
        back: 267,
        next: 269, //母亲穿越
    },{
        id:269,
        text: "我穿越了回来，仰面躺在床上，之前随便从书架上取下来的小说掉落在了地板上。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/背景1.png",
        back: 268,
        next: 270,
    },{
        id:270,
        text: "我捡了起来，随后又吃了一惊，手里的书也又掉了。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/背景1.png",
        back: 269,
        next: 271,
    },{
        id:271,
        text: "书的封皮上写着，作者，张勇齐。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/背景1.png",
        back: 270,
        next: 272,
    },{
        id:272,
        text: "我颤抖着，翻开了书，一行行读了下去，直到我看见。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/背景1.png",
        back: 271,
        next: 273,
    },{
        id:273,
        text: "我好像明白了什么，我感觉我的身体抖得厉害，我把书翻到了最后。",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片20.png",
        back: 272,
        next: 274,  
    },{
        id:274,
        text: "故事的最后写着，“钱筱慧锁上门，走向警察局，向警察坦白了这一切。”",
        name: "",
        saylihui: "",
        backlihui: "",
        background: "素材/背景/图片20.png",
        back: 273,
        next: 275,
    },{
        id:275,
        text: "母亲......母亲......",
        name:"我：",
        saylihui: "素材/立绘/主角.png",
        backlihui: "",
        background: "素材/背景/图片20.png",
        back: 274,
        next: 600,// 跳转到结尾
    },
];

var currentDialogue = localStorage.getItem("CD") || 0;
var textFullyShown = false;
var selectedOption = -1;
var interval;
var textSpeed =localStorage.getItem("textSpeed") || 50;
var volume = localStorage.getItem("volume") || 100;

function showMessage() {
    document.getElementById("button1").style.display = "none";
    document.getElementById("button2").style.display = "none";
    selectedOption = -1;
    textFullyShown = false; // 重置文本完全显示状态
    document.getElementById("text").innerHTML = "";
    document.getElementById("name").innerHTML = dialogues[currentDialogue].name;
    document.getElementById("background").src = dialogues[currentDialogue].background;

    if (dialogues[currentDialogue].saylihui) {
        document.getElementById("saylihui").src = dialogues[currentDialogue].saylihui;
        document.getElementById("saylihui").style.display = "block";
    } else {
        document.getElementById("saylihui").style.display = "none";
    }

    if (dialogues[currentDialogue].backlihui) {
        document.getElementById("backlihui").src = dialogues[currentDialogue].backlihui;
        document.getElementById("backlihui").style.display = "block";
    } else {
        document.getElementById("backlihui").style.display = "none";
    }

    if (dialogues[currentDialogue].music) {
        document.getElementById("music").src = dialogues[currentDialogue].music;
        document.getElementById("music").play();
        document.getElementById("music").volume = volume/100;
    }//播放音乐

    let index = 0;
    let text = dialogues[currentDialogue].text;
    interval = setInterval(function() {
        document.getElementById("text").innerHTML += text[index];
        index++;
        if (index >= text.length) {
            clearInterval(interval);
            textFullyShown = true;
            CheckCG();
            showOptions();
        }
    }, 101-textSpeed);
}

function showOptions() {
    if (dialogues[currentDialogue].option) {
        switch (dialogues[currentDialogue].option.length) {
            case 2:
                document.getElementById("button1").style.display = "inline-block";
                document.getElementById("button2").style.display = "inline-block";
                document.getElementById("button1").style.top = "30%";
                document.getElementById("button2").style.top = "50%";
                document.getElementById("button1").innerHTML = dialogues[currentDialogue].option[0].text;
                document.getElementById("button2").innerHTML = dialogues[currentDialogue].option[1].text;
                document.getElementById("button1").onclick = function () {
                    selectedOption = 0;
                    getNextDialogue(selectedOption);
                    showMessage();
                };
                document.getElementById("button2").onclick = function () {
                    selectedOption = 1;
                    getNextDialogue(selectedOption);
                    showMessage();
                };
                break;
            case 1:
                document.getElementById("button1").style.display = "inline-block";
                document.getElementById("button1").style.top = "40%";
                document.getElementById("button1").innerHTML = dialogues[currentDialogue].option[0].text;
                document.getElementById("button2").style.display = "none";
                document.getElementById("button1").onclick = function () {
                    selectedOption = 0;
                    getNextDialogue(selectedOption);
                    showMessage();
                };
                break;
        }
    } else {
        document.getElementById("button1").style.display = "none";
        document.getElementById("button2").style.display = "none";
    }
}

function getNextDialogue(selectedOption) {
    if (dialogues[currentDialogue].option) {
        currentDialogue = dialogues[currentDialogue].option[selectedOption].next;
    } else {
        currentDialogue = dialogues[currentDialogue].next;
    }
}
function getBack() {
    currentDialogue = dialogues[currentDialogue].back;
    showMessage();
}

document.addEventListener('click', function() {
    if (textFullyShown) {
        if (dialogues[currentDialogue].option) {
            return;
        }
        getNextDialogue();
        showMessage();
    } else {
        clearInterval(interval);
        document.getElementById("text").innerHTML = dialogues[currentDialogue].text;
        textFullyShown = true;
        CheckCG();
        showOptions();
    }
});
function CheckCG(){
    if(dialogues[currentDialogue].next==300){//坏结局
        location.href = "../video/死亡.html";
    }
    if(dialogues[currentDialogue].next==600){//结局
        location.href = "../video/结尾.html";
    }
    if(dialogues[currentDialogue].next==164){//五子棋
        location.href = "../五子棋/wuziqi.html";
    }
    if(dialogues[currentDialogue].next==76){//拼图
        location.href = "../拼图/pintu.html";
    }
    if(dialogues[currentDialogue].next==12){//开头穿越
        location.href = "../video/开头穿越.html";
    }
    if(dialogues[currentDialogue].id==268){//母亲穿越
        location.href = "../video/母亲穿越.html";
    }
    if(dialogues[currentDialogue].id==262){//保安穿越
        location.href = "../video/保安穿越.html";
    }
}
function save(){
    localStorage.setItem("CD", currentDialogue);
    location.href = "../save/save.html";
}
function toSetting(){
    localStorage.setItem("CD", currentDialogue);
    location.href = "../homepage/setting2.html";
}
function toHome(){
    localStorage.setItem("CD", currentDialogue);
    location.href = "../homepage/homepage.html";
}
function initGame() {
    showMessage();
}
window.addEventListener("load", function () {
    initGame();
});
